// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"wire-go/provider"
)

// Injectors from wire.go:

// InitializeEvent 声明injector的函数签名
func InitializeEvent(msg string) provider.Event {
	message := provider.NewMessage(msg)
	greeter := provider.NewGreeter(message)
	event := provider.NewEvent(greeter)
	return event
}

// wire.go:

// EventSet Event通常是一起使用的一个集合，使用wire.NewSet进行组合
var EventSet = wire.NewSet(provider.NewEvent, provider.NewMessage, provider.NewGreeter)
